name: End to End Deployment

on:
  workflow_dispatch:
    inputs:
      metadata:
        description: 'Metadata Descriptor'
        required: true
        type: string
        default: ''


jobs:
    deployment:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Set up current working directory with the repo contents
        - uses: actions/checkout@v2
        - name: test
          id: test
          run: echo ::set-output name=runeks::true
        - name: eks
          if: steps.test.outputs.runeks == 'true'
          uses: ./.github/workflows/deploy_eks_callable.yml
          #secrets: inherit