
name: End to End Deployment

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      metadata:
        description: 'Metadata Descriptor'
        required: true
        type: string
        default: ''


jobs:
    deploy-eks:
      uses: ./.github/workflows/deploy_eks_callable.yml
      secrets: inherit

    deployment:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Set up current working directory with the repo contents
        - uses: actions/checkout@v2