name: Install Stack (Management Console Only)
on:
  workflow_dispatch:
    branches: [ main ]
    inputs:
      METADATA:
        description: 'UCS Metadata Definition'
        required: true
        type: string
        default: ''
jobs:
  run_unity_job:
    runs-on: ubuntu-latest
    name: Parse Metadata and Execute
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'unity-sds/unity-cs-infra' 
      - name: Check path
        run: echo "path ${PWD}" && ls -al
      - name: print env
        run: echo "${{inputs.METADATA}}"
      - name: Print inputs
        uses: actions/github-script@v5
        with:
          script: |
            console.log(`Workflow Inputs: ${JSON.stringify(process.env, null, 2)}`)
      - name: Print trigger type
        uses: actions/github-script@v5
        with:
          script: |
            console.log(`Trigger Event Type: ${context.eventName}`)
      - name: install act
        run: curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | bash && echo "${PWD}/bin" >> $GITHUB_PATH

      - name: test
        run: echo "-P ubuntu-latest=catthehacker/ubuntu:act-latest" > ~/.actrc &&
             echo "-P ubuntu-22.04=catthehacker/ubuntu:act-22.04" >> ~/.actrc &&
             echo "-P ubuntu-20.04=catthehacker/ubuntu:act-20.04" >> ~/.actrc &&
             echo "-P ubuntu-18.04=catthehacker/ubuntu:act-18.04" >> ~/.actrc
      - name: Unity custom action step
        uses: unity-sds/unity-cs-action@main
        id: main_action_run
        with:
          token: ${{ secrets.TOKEN }}
          ucsmetadata: ${{ inputs.METADATA }}
