name: Install Stack (Management Console Only)
on:
  workflow_dispatch:
    branches: [ main ]
    inputs:
      METADATA:
        description: 'UCS Metadata Definition'
        required: true
        type: string
        default: ''
jobs:
  run_unity_job:
    runs-on: ubuntu-latest
    name: Parse Metadata and Execute
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: print env
        run: echo "${{inputs.METADATA}}"
      - name: Print inputs
        uses: actions/github-script@v5
        with:
          script: |
            console.log(`Workflow Inputs: ${JSON.stringify(process.env, null, 2)}`)
      - name: Print trigger type
        uses: actions/github-script@v5
        with:
          script: |
            console.log(`Trigger Event Type: ${context.eventName}`)
      - name: Unity custom action step
        uses: unity-sds/unity-cs-action@main
        id: main_action_run
        with:
          token: ${{ secrets.TOKEN }}
          ucsmetadata: ${{ inputs.METADATA }}
