# Unity teardown workflow

name: CI Teardown

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ ucs-template ]
  pull_request:
    branches: [ ucs-template ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ ucs-template ]

# These steps will tear down a unity project using the provided terraform scripts
jobs:
  # This workflow contains a single job called "teardown"
  teardown:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Creates a terraform destroy plan
      - name: Terraform Teardown Plan
        working-directory: ./resources/deployable/terraform-unity
#        if: github.ref == 'refs/heads/smolenski_tf_test' && github.event_name == 'push'
        run: terraform plan -destroy

