on:
  workflow_dispatch:
    branches: [ main ]
    inputs:
      KEY:
        description: 'Access Key ID'
        required: false
        type: string
        default: ''
      SECRET:
        description: 'Access Secret Key ID'
        required: false
        type: string
        default: ''
      TOKEN:
        description: 'AWS Session Token'
        required: false
        type: string
        default: ''
jobs:
  run_unity_job:
    runs-on: ubuntu-latest
    name: Parse Metadata and Execute
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unity custom action step
        uses: unity-sds/unity-cs-action@fb98a6da3f3175b771fab2ef728b0d96646334f2
        id: hello
        with:
          awskey: ${{ inputs.KEY }}
          awssecret: ${{ inputs.SECRET }}
          awstoken: ${{ inputs.TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ucsmetadata: '{
  "metadataVersion": "unity-cs-0.1",
  "deploymentName": "some name for the deployment of services",
  "services": [
    {
        "name": "unity-sps-prototype",
        "source": "unity-sds/unity-sps-prototype",
        "version": "xxx",
        "branch": "main"
    }
  ],
  "extensions": {
    "kubernetes": {
      "clustername": "testclustertomsun6",
      "owner": "tom",
      "projectname": "testproject",
      "nodegroups": {
        "group1": {
          "instancetype": "m5.xlarge",
          "nodecount": "3"
        }
      }
    }
  }
}'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.eksmeta }}"
